// <auto-generated />
namespace ShopThoiTrang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class edit_entity_Foreign_all_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_entity_Foreign_all_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202112220944423_edit_entity_Foreign_all_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
