// <auto-generated />
namespace ShopThoiTrang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class createTable_Permission_UserRoles_UserPermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createTable_Permission_UserRoles_UserPermission));
        
        string IMigrationMetadata.Id
        {
            get { return "202202160623179_createTable_Permission_UserRoles_UserPermission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
