// <auto-generated />
namespace ShopThoiTrang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtableattribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableattribute));
        
        string IMigrationMetadata.Id
        {
            get { return "202201150425267_add-table-attribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
